# Formative 

<img src="music.jpg">

Music Experts have been trying for a long time to understand sound and what differentiates one song from another. How to visualize sound. What makes a tone different from another. This dataset consists of the features extracted from a music audio file. for simplicity sake we have considered classifying the music into 3 categories: classical, disco and jazz.

Attributes:
1.	len : Length of the music
2.	cs_mean: Mean of intensity of pitches
3.	cs_var: Variance of Intensity of pitches
4.	rms_mean: Mean of RMS of voltage
5.	rms_var: Variance of RMS of voltage
6.	sb_mean: Mean of spectral bandwidth
7.	sb_var: Variance of spectral bandwidth
8.	ro_var: Mean of roll off frequency filter
9.	ro_mean: Variance of roll off frequency filter
10.	zcr_mean: Mean of zero crossing rate
11.	zcr_var: Variance of zero crossing rate
12.	har_mean: Mean of harmony
13.	har_var: Variance of harmony
14.	tempo: Music tempo
15.	label: classical, disco and jazz are 3 types of music

In [57]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [58]:
music = pd.read_csv('music.csv')
music.head()

,len,cs_mean,cs_var,rms_mean,rms_var,sb_mean,sb_var,ro_mean,ro_var,zcr_mean,zcr_var,har_mean,har_var,tempo,label
0,661794,0.252392,0.084153,0.036245,0.000221,1559.005740,43682.97327,2716.306158,299398.3072,0.098223,0.000431,-0.000047,0.001230,95.703125,classical
1,661794,0.214995,0.085010,0.030625,0.000161,1441.243134,32378.72969,2387.729130,368797.1379,0.087766,0.000630,-0.000051,0.001047,112.347147,classical
2,661794,0.277958,0.083759,0.043860,0.000193,1600.115744,31200.89904,2785.294011,274835.3889,0.090046,0.000395,-0.000020,0.001638,99.384014,classical
3,661794,0.234229,0.083451,0.029442,0.000357,1499.439342,60196.22756,2916.000387,499393.9317,0.108946,0.001161,-0.000035,0.001164,71.777344,classical
4,661794,0.221574,0.085000,0.042316,0.000209,1646.064010,25963.45828,3174.931743,333266.8791,0.112857,0.000835,-0.000059,0.001838,161.499023,classical

In [92]:
music.shape

(300, 15)

Q1: Check for missing values. Impute with mean if any missing values are present. (5 Marks)

Hint: Use SimpleImputer

In [59]:
music.isnull().sum()

len          0
cs_mean      0
cs_var       0
rms_mean     0
rms_var     16
sb_mean      0
sb_var       0
ro_mean      0
ro_var       0
zcr_mean     0
zcr_var      0
har_mean     0
har_var      0
tempo        0
label        0
dtype: int64

In [63]:
# Write the answer here
# Write the answer here

from sklearn.impute import SimpleImputer
import numpy as np
se=SimpleImputer(missing_values=np.nan, strategy='mean')
music['rms_var'] = se.fit_transform(music[['rms_var']])

In [64]:
music.isnull().sum()

len         0
cs_mean     0
cs_var      0
rms_mean    0
rms_var     0
sb_mean     0
sb_var      0
ro_mean     0
ro_var      0
zcr_mean    0
zcr_var     0
har_mean    0
har_var     0
tempo       0
label       0
dtype: int64

Q2: Apply min max scaling for all the attributes. (5 Marks)

In [70]:
scaling_data= music.drop(['label','len'],axis=1)  # we can't scale categorical so seprate that
scaling_data

,cs_mean,cs_var,rms_mean,rms_var,sb_mean,sb_var,ro_mean,ro_var,zcr_mean,zcr_var,har_mean,har_var,tempo
0,0.252392,0.084153,0.036245,0.000221,1559.005740,43682.97327,2716.306158,2.993983e+05,0.098223,0.000431,-4.660000e-05,0.001230,95.703125
1,0.214995,0.085010,0.030625,0.000161,1441.243134,32378.72969,2387.729130,3.687971e+05,0.087766,0.000630,-5.130000e-05,0.001047,112.347147
2,0.277958,0.083759,0.043860,0.000193,1600.115744,31200.89904,2785.294011,2.748354e+05,0.090046,0.000395,-1.970000e-05,0.001638,99.384014
3,0.234229,0.083451,0.029442,0.000357,1499.439342,60196.22756,2916.000387,4.993939e+05,0.108946,0.001161,-3.540000e-05,0.001164,71.777344
4,0.221574,0.085000,0.042316,0.000209,1646.064010,25963.45828,3174.931743,3.332669e+05,0.112857,0.000835,-5.910000e-05,0.001838,161.499023
...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,0.311235,0.090341,0.068182,0.000695,2215.592498,126407.71400,4282.076453,1.763819e+06,0.063363,0.000846,-4.400000e-06,0.004430,117.453835
296,0.298770,0.093177,0.044420,0.000463,2083.706520,178343.20990,4008.631419,2.667886e+06,0.077717,0.002115,1.590000e-09,0.001968,135.999178
297,0.224049,0.091032,0.021187,0.000184,1753.640845,186895.36210,2343.555254,2.332215e+06,0.039908,0.000475,-6.780000e-06,0.000593,86.132812
298,0.327593,0.091018,0.060162,0.000455,2230.789208,106215.47420,4357.067956,1.694619e+06,0.058131,0.001241,-4.310000e-06,0.003096,80.749512
299,0.295912,0.096349,0.039269,0.000423,2014.187546,165836.72930,3375.924959,2.285388e+06,0.046179,0.000538,-1.230000e-06,0.001636,135.999178

In [83]:
# Write the answer here


from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
scaled_data = sc.fit_transform(scaling_data)
scaled_data

array([[0.20304477, 0.41595209, 0.10725852, ..., 0.6327475 , 0.01814049,
        0.22633745],
       [0.10866334, 0.44113925, 0.08779475, ..., 0.6326332 , 0.01532788,
        0.31884058],
       [0.26756807, 0.40434995, 0.13363171, ..., 0.6334017 , 0.0244234 ,
        0.24679487],
       ...,
       [0.13151389, 0.61826569, 0.05510477, ..., 0.63371591, 0.00836068,
        0.17314815],
       [0.39283649, 0.61786643, 0.19009319, ..., 0.63377598, 0.04683038,
        0.14322917],
       [0.3128792 , 0.7746373 , 0.11773202, ..., 0.63385088, 0.02438757,
        0.4502924 ]])

In [84]:
scaled_data= pd.DataFrame(scaled_data)
scaled_data

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0.203045,0.415952,0.107259,0.009304,0.264336,0.049589,0.262010,0.040647,0.289822,0.022816,0.632748,0.018140,0.226337
1,0.108663,0.441139,0.087795,0.004388,0.217238,0.029481,0.218246,0.050555,0.244377,0.034497,0.632633,0.015328,0.318841
2,0.267568,0.404350,0.133632,0.006991,0.280778,0.027386,0.271198,0.037140,0.254286,0.020685,0.633402,0.024423,0.246795
3,0.157206,0.395298,0.083697,0.020471,0.240513,0.078963,0.288607,0.069200,0.336426,0.065789,0.633020,0.017128,0.093364
4,0.125267,0.440843,0.128287,0.008370,0.299154,0.018070,0.323095,0.045482,0.353422,0.046593,0.632444,0.027486,0.592014
...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,0.351551,0.597946,0.217871,0.048336,0.526932,0.196739,0.470557,0.249716,0.138324,0.047228,0.633774,0.067329,0.347222
296,0.320093,0.681341,0.135572,0.029260,0.474185,0.289121,0.434137,0.378786,0.200706,0.121976,0.633881,0.029493,0.450292
297,0.131514,0.618266,0.055105,0.006273,0.342179,0.304333,0.212363,0.330863,0.036392,0.025360,0.633716,0.008361,0.173148
298,0.392836,0.617866,0.190093,0.028553,0.533009,0.160821,0.480545,0.239837,0.115589,0.070536,0.633776,0.046830,0.143229
299,0.312879,0.774637,0.117732,0.025902,0.446382,0.266874,0.349865,0.324178,0.063647,0.029082,0.633851,0.024388,0.450292

Q3: Split the data into test and train and apply Logistic Regression to predict the category of the music. (10 Marks)

In [85]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
music['label']=le.fit_transform(music['label'])
y=music['label'].values
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [86]:
scaled_data

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0.203045,0.415952,0.107259,0.009304,0.264336,0.049589,0.262010,0.040647,0.289822,0.022816,0.632748,0.018140,0.226337
1,0.108663,0.441139,0.087795,0.004388,0.217238,0.029481,0.218246,0.050555,0.244377,0.034497,0.632633,0.015328,0.318841
2,0.267568,0.404350,0.133632,0.006991,0.280778,0.027386,0.271198,0.037140,0.254286,0.020685,0.633402,0.024423,0.246795
3,0.157206,0.395298,0.083697,0.020471,0.240513,0.078963,0.288607,0.069200,0.336426,0.065789,0.633020,0.017128,0.093364
4,0.125267,0.440843,0.128287,0.008370,0.299154,0.018070,0.323095,0.045482,0.353422,0.046593,0.632444,0.027486,0.592014
...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,0.351551,0.597946,0.217871,0.048336,0.526932,0.196739,0.470557,0.249716,0.138324,0.047228,0.633774,0.067329,0.347222
296,0.320093,0.681341,0.135572,0.029260,0.474185,0.289121,0.434137,0.378786,0.200706,0.121976,0.633881,0.029493,0.450292
297,0.131514,0.618266,0.055105,0.006273,0.342179,0.304333,0.212363,0.330863,0.036392,0.025360,0.633716,0.008361,0.173148
298,0.392836,0.617866,0.190093,0.028553,0.533009,0.160821,0.480545,0.239837,0.115589,0.070536,0.633776,0.046830,0.143229
299,0.312879,0.774637,0.117732,0.025902,0.446382,0.266874,0.349865,0.324178,0.063647,0.029082,0.633851,0.024388,0.450292

In [100]:
from sklearn.model_selection import train_test_split

X =scaled_data #music.drop('label', axis=1)
y = y
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

(240,)

In [102]:
X_train.shape

(240, 13)

In [104]:
# Write the answer here

from sklearn.linear_model import LogisticRegression
model_cls=LogisticRegression()
model_cls.fit(X_train,y_train)

LogisticRegression()

In [106]:
model_cls.predict(X_test)

array([0, 0, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0, 1, 1, 2, 0, 2, 0, 1, 1, 1, 2,
       1, 0, 2, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 2, 2, 0, 2, 0, 1, 1, 2, 1,
       1, 1, 2, 1, 0, 0, 1, 1, 1, 1, 1, 1, 2, 0, 1, 2], dtype=int64)

Q4: Find out the best regularization parameters for Logistic Regression using GridSearchCV. (10 Marks)

Hint: use the penalty and solver parameters

In [109]:
# Write the answer here
from sklearn.model_selection import GridSearchCV

param={"penalty":["l1", "l2", "elasticnet"] ,
                  
        "solver":["newton-cg", "lbfgs", "liblinear", "sag", "saga"]
                  }

model_gscv=GridSearchCV(LogisticRegression(),param_grid=param,cv=2)
model_gscv.fit(X_train,y_train)

GridSearchCV(cv=2, estimator=LogisticRegression(),
             param_grid={'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']})

Q5: Apply Decision Tree Classifier, Bagging Classifier and Random Forest Classifier and compare it with Logistic regression (10 marks)

In [110]:
# Write the answer here
#1] Decision tree classifier
from sklearn.tree import DecisionTreeClassifier
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train,y_train)

DecisionTreeClassifier(random_state=0)

In [111]:
clf_dt.score(X_test,y_test) # decision tree classifier score

0.8666666666666667

In [120]:
from sklearn.ensemble import BaggingClassifier

bag_model = BaggingClassifier(base_estimator = clf_dt,
                          n_estimators = 1000,
                          
            )
bag_model=bag_model.fit(X_train,y_train)
ytest_pred=bag_model.predict(X_test)
print(bag_model.score(X_test, y_test))

0.8666666666666667

In [119]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(n_estimators = 1000) 
 
rf_clf.fit(X_train, y_train)
 
rf_clf.score(X_test,y_test)

0.8833333333333333

In [ ]:
# As we can see random forest gives higher accuracy score